### PR TITLE
Update README.md removing comment about auto port discovery

### PR DESCRIPTION
**Pull request by Gamester17**
Update README.md removing comment about auto port discovery

### CODE REVIEW

**Comment by sanyatuning** [comment]
We can do auto discovery. I will try to code it this week.

**Comment by Hedda** [comment]
FYI, I submitted similar request https://github.com/sanyatuning/zigpy-cc/issues/20 and for zigpy too here https://github.com/zigpy/zigpy/issues/309

Btw, I believe that @doudz implemented ZiGate USB-port auto-discovery for ZHA in zigpy-zigate? 

https://www.home-assistant.io/integrations/zha/

 _"If you are use ZiGate, you have to use some special usb_path configuration: ZiGate USB TTL or DIN: /dev/ttyUSB0 or auto to auto discover the zigate"_

https://github.com/doudz/zigpy-zigate

PS: Does anyone know if USB-port auto-discovery is supported by bellows or others for zigpy?

**Comment by Hedda** [comment]
Would it also be possible to implement handling of serial port disconnects/reconnects?

This is kind of related serial-port auto-discovery but created a separate feature request:

https://github.com/sanyatuning/zigpy-cc/issues/22

Also see related issue:

https://github.com/sanyatuning/zigpy-cc/issues/15

The main reason for that is when using ser2net and socat to use serial device over the network.

Problem is if network temporarly goes down then it can currently reconnect to recover connection.

How-do for that is here: https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

Reference:

https://community.home-assistant.io/t/add-network-protocol-support-to-zigbee-and-zwave-integrations/136056

https://github.com/Danielhiversen/pyRFXtrx/pull/85

https://github.com/zigpy/bellows/issues/183

https://github.com/zigpy/zigpy/issues/297

**Comment by sanyatuning** [comment]
i do both, auto discovery and reconnect, so closing this now

**Pull request closed without merging**
